### ISSUE TITLE
Idempotency for Server Hardware iLO firmware version (Always returns changed instead of OK)

### ISSUE THREAD

**Issue by liamwh** [HewlettPackard/oneview-ansible-collection#103]
### Scenario/Intent
Idempotent deployment of servers with accurate OK and Changed results from Ansible. Using the ilo_firmware_version_updated task always returns a result of changed.

### Environment Details
 - **Module Version:** 6.0.0
 - **Ansible Version:** ansible 2.10.7
 - **OneView Appliance Version:** 5.50.00-0426657
 - **OneView Client API Version:** 2200
 - **Python Version:** python version = 3.8.5
 - **python-hpOneView SDK Version:** 6.0.0
 - **Platform:** ubuntu docker container running Ansible

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/23312359/112647895-42d5d980-8e49-11eb-96dd-5425bfe2e677.png)

### Expected Result
Status OK returned from Ansible, not Changed.

### Actual Result
![image](https://user-images.githubusercontent.com/23312359/112647782-289bfb80-8e49-11eb-8770-0df51bbc6e8e.png)
![image](https://user-images.githubusercontent.com/23312359/112647738-1c17a300-8e49-11eb-8631-0e424ac69cfa.png)

![image](https://user-images.githubusercontent.com/23312359/112647661-0ace9680-8e49-11eb-8586-4d06db910933.png)

**Comment by nabhajit-ray** [comment]
Thanks for migrating the issue from ansible repository. We will pick this up soon and  keep you updated.

**Comment by VenkateshRavula** [comment]
The fix is merged to master. Please pull the latest master and retry the scenario.
