### ISSUE TITLE
oneview_server_hardware module is not idempotent

### ISSUE THREAD

**Issue by mlowcher61** [HewlettPackard/oneview-ansible-collection#106]
oneview_server_hardware module is not idempotent. It works the first time it is run. If you run it a second time with the same vars, it errors in red stating the server already exists. This will break workflows. It needs to report server already exists in green so it completes as successful

**Comment by nabhajit-ray** [comment]
We will look into this. Thanks

**Comment by VenkateshRavula** [comment]
We have fixed the idempotency issues for oneview_server_hardware module and merged it to master.
If you are using github repository for ansible collections, you can pull the master and build and install the updated collections for the changes to be reflected in your environment.
If you are using ansible-galaxy, then please wait until the next release.
