### ISSUE TITLE
Roles are really examples

### ISSUE THREAD

**Issue by mlowcher61** [HewlettPackard/oneview-ansible-collection#107]
Some roles need to be edited to work properly. They are more examples than working roles. For instance. The oneview_hypervisor_manager module will create, update, power off, power on delete and re-create the server. This makes it unusable as a called role from a requirements.yml file. 
You will need to edit the tasks to work properly, then when you update the project in Ansible Tower, it will re-download the roles from Galaxy or Automation hub and overwrite any changes that were made. 
These "roles" should be moved into a directory called "examples" and the roles should be made usable.

**Comment by nabhajit-ray** [comment]
Thanks @mlowcher61   for the suggestions. We will look into it and get back to you.

**Comment by AsisBagga** [comment]
@mlowcher61 Hi, thank you for your suggestion. Unfortunately, as you know, we don't have these roles to be installed from ansible-galaxy yet, but we are working on it. However, I can provide a workaround for using our roles as a separate entity to be placed in roles default path. 
**Prerequisite:** you need to install the `oneview-ansible-collection` 
Move your desired roles from collections to default roles path i.e. `~/.ansible/roles ` 
Set Ansible Library and Module Utils path as follows:-
`$ export ANSIBLE_LIBRARY=$HOME/.ansible/collections/path-to-oneview-ansible-collection-library`
`$ export ANSIBLE_MODULE_UTILS=$HOME/.ansible/collections/path-to-oneview-ansible-collection-library/module_utils/`
Update your playbook with your roles as below, and run it.
```
---
- hosts: all
  roles:
    - oneview_hypervisor_manager
```
P.S: you will need to update the config-file path in main.yaml in defaults directory inside the role.

**Comment by AsisBagga** [comment]
@mlowcher61 Hi, since we have not received any response from you, I believe the suggested actions worked. I'll be proceeding with closing this issue, if you have any queries with regards to the same, please feel free to re-open this. Thank you.
