### ISSUE TITLE
Gather facts about a ID Pools IPV4 Subnet by name doesnt supported

### ISSUE THREAD

**Issue by grsoratoor** [HewlettPackard/oneview-ansible-collection#131]
Gather facts about an ID Pools IPV4 Subnet by name is not supported. It was supported before collections. backward compatibility is missing.

The file that affecting this issue is
https://github.com/HewlettPackard/oneview-ansible-collection/blob/master/plugins/modules/oneview_id_pools_ipv4_subnet_facts.py

**Comment by grsoratoor** [comment]
- name: Gather facts about a ID Pools IPV4 Subnet by name
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ config_file_path }}"
    name: IPV4Subnet_01

This example is not working

**Comment by chebroluharika** [comment]
Hi @grsoratoor 
Thanks for pointing out. We are working on a fix for this and provide the solution as early as possible.
