### ISSUE TITLE
oneview_server_profile TypeError: sequence item 0: expected str instance, NoneType found

### ISSUE THREAD

**Issue by cavamagie** [HewlettPackard/oneview-ansible-collection#143]
hello 
i try to use the sample

Create a Server Profile with connections

 but receive the error

The full traceback is:
Traceback (most recent call last):
  File "/home/u86587@b05387.adgruppo.priv/.ansible/tmp/ansible-tmp-1632998751.61551-67691-19266064946261/AnsiballZ_oneview_server_profile.py", line 102, in <module>
    _ansiballz_main()
  File "/home/u86587@b05387.adgruppo.priv/.ansible/tmp/ansible-tmp-1632998751.61551-67691-19266064946261/AnsiballZ_oneview_server_profile.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/u86587@b05387.adgruppo.priv/.ansible/tmp/ansible-tmp-1632998751.61551-67691-19266064946261/AnsiballZ_oneview_server_profile.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.hpe.oneview.plugins.modules.oneview_server_profile', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 693, in <module>
  File "/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 689, in main
  File "/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/module_utils/oneview.py", line 633, in run
  File "/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 284, in execute_module
  File "/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 324, in __present
  File "/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 451, in __create_profile
  File "/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 683, in _auto_assign_server_profile
  File "/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 540, in __get_available_server_hardware_uri
TypeError: sequence item 0: expected str instance, NoneType found
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/u86587@b05387.adgruppo.priv/.ansible/tmp/ansible-tmp-1632998751.61551-67691-19266064946261/AnsiballZ_oneview_server_profile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/u86587@b05387.adgruppo.priv/.ansible/tmp/ansible-tmp-1632998751.61551-67691-19266064946261/AnsiballZ_oneview_server_profile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/u86587@b05387.adgruppo.priv/.ansible/tmp/ansible-tmp-1632998751.61551-67691-19266064946261/AnsiballZ_oneview_server_profile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hpe.oneview.plugins.modules.oneview_server_profile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 693, in <module>\n  File \"/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 689, in main\n  File \"/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/module_utils/oneview.py\", line 633, in run\n  File \"/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 284, in execute_module\n  File \"/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 324, in __present\n  File \"/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 451, in __create_profile\n  File \"/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 683, in _auto_assign_server_profile\n  File \"/tmp/ansible_oneview_server_profile_payload_sypcl5im/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 540, in __get_available_server_hardware_uri\nTypeError: sequence item 0: expected str instance, NoneType found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

  - name: Create a Server Profile with connections
    oneview_server_profile:
       config: "config.json"
       #state: "present"
       data:
         name: "demo"
         description: Server Profile with connections created from a selected Server Profile Templa
         serverHardwareTypeName: "SY 480 Gen10 1"
         connectionSettings:
           connections:
           - id: 1
             name: connection1
             functionType: Ethernet
             portId: Auto
             requestedMbps: 2500
             networkName: "vmwab01041-mgmt"           
    delegate_to: localhost

ansible 2.9.26
  config file = None
  configured module search path = ['/home/u86587@b05387.adgruppo.priv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by cavamagie** [comment]
setting
auto_assign_server_hardware: False

works

**Comment by davmartini** [comment]
Hello,

I have exactly the same problem to provision available hardware from profile template.


    - name: Create a Server Profile from a Server Profile Template
      oneview_server_profile:
        auto_assign_server_hardware: True
        data:
          serverProfileTemplateName: "{{ server_template_name }}"
          name: "test"
          description: "test"
        params:
          force: True
      delegate_to: localhost
      register: result


TypeError: sequence item 0: expected str instance, NoneType found


Any idea?

Thank you for your help.

**Comment by chebroluharika** [comment]
Hi @davmartini ,
Can you please send us the error trace?

**Comment by davmartini** [comment]
Hi @chebroluharika 

{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1639148686.1479053-92-276581402971365/AnsiballZ_oneview_server_profile.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1639148686.1479053-92-276581402971365/AnsiballZ_oneview_server_profile.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1639148686.1479053-92-276581402971365/AnsiballZ_oneview_server_profile.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hpe.oneview.plugins.modules.oneview_server_profile', init_globals=dict(_module_fqn='ansible_collections.hpe.oneview.plugins.modules.oneview_server_profile', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 702, in <module>\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 698, in main\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/module_utils/oneview.py\", line 648, in run\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 287, in execute_module\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 327, in __present\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 457, in __create_profile\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 692, in _auto_assign_server_profile\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 546, in __get_available_server_hardware_uri\nTypeError: sequence item 0: expected str instance, NoneType found\n",
  "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1639148686.1479053-92-276581402971365/AnsiballZ_oneview_server_profile.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1639148686.1479053-92-276581402971365/AnsiballZ_oneview_server_profile.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1639148686.1479053-92-276581402971365/AnsiballZ_oneview_server_profile.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hpe.oneview.plugins.modules.oneview_server_profile', init_globals=dict(_module_fqn='ansible_collections.hpe.oneview.plugins.modules.oneview_server_profile', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 702, in <module>\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 698, in main\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/module_utils/oneview.py\", line 648, in run\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 287, in execute_module\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 327, in __present\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 457, in __create_profile\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 692, in _auto_assign_server_profile\n  File \"/tmp/ansible_oneview_server_profile_payload_5i6lsjhn/ansible_oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 546, in __get_available_server_hardware_uri\nTypeError: sequence item 0: expected str instance, NoneType found\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false
}

**Comment by chebroluharika** [comment]
Hi @davmartini ,
If possible can you please tell me whats the username you are using for OneView login because thats related to this scenario as you don’t have initialscopeuris.

**Comment by dobey-xx** [comment]
Hi, @chebroluharika,

This still seems a valid issue, getting the follow error when trying to create a profile:

\"/tmp/ansible_hpe.oneview.oneview_server_profile_payload___kih52j/ansible_hpe.oneview.oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 337, in __present\n  File \"/tmp/ansible_hpe.oneview.oneview_server_profile_payload___kih52j/ansible_hpe.oneview.oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 467, in __create_profile\n  File \"/tmp/ansible_hpe.oneview.oneview_server_profile_payload___kih52j/ansible_hpe.oneview.oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 702, in _auto_assign_server_profile\n  File \"/tmp/ansible_hpe.oneview.oneview_server_profile_payload___kih52j/ansible_hpe.oneview.oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py\", line 556, in __get_available_server_hardware_uri\nTypeError: sequence item 0: expected str instance, NoneType found\n",

It's in a test environment so the user is Infrastructure admin. I followed the example as described here: https://github.com/HewlettPackard/oneview-ansible-collection/blob/master/roles/oneview_server_profile/tasks/main.yml
