### ISSUE TITLE
Labels - Get the resources associated with label

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/oneview-ansible-collection#150]
## Scenario/Intent

Hello,

I am trying to get a list of resources associated with a label by name. However the fact doesn't return anything related to resources.

## Environment Details

- OneView Ansible Collection: v6.3.0
- OneView Appliance Version: 6.30
- Ansible version: 2.11.6
- Python version: 3.6.8

## Expected Result

When getting facts from a label by name, the resources associated with this label are also returned.
Can it be done with the Ansible SDK ? In the [HPE OneView SDK for Python](https://github.com/HewlettPackard/oneview-python/blob/master/hpeOneView/resources/search/labels.py) we seem to be able to do it.

## Actual Result

```
"ansible_facts": {
            "labels": [
                {
                    "category": "labels",
                    "created": "2021-10-13T14:53:13.626Z",
                    "eTag": "1",
                    "modified": "2021-10-13T14:53:13.626Z",
                    "name": "test",
                    "type": "Label",
                    "uri": "/rest/labels/1"
                }
            ]
        }
```

**Comment by chebroluharika** [comment]
Hi @ClaireHayard, can you please try it now after taking the latest code and rebuilding the collection.
