### ISSUE TITLE
OneView Session limit exceeded issue

### ISSUE THREAD

**Issue by pnadarge** [HewlettPackard/oneview-ansible-collection#182]
OneView creates a new session for every task in ansible to delete and create a server profile from a server profile template. This led to OneView reaching its session limit, making it impossible to access OneView through ansible and also any of the OneView APIs. Is there a way we can use a session id to re-login for each task so that we do not exceed the limit?

**Comment by pnadarge** [comment]
Opened an issue for OneView session limit

**Comment by alisha-k-kalladassery** [comment]
We are checking on this.

**Comment by alisha-k-kalladassery** [comment]
To reuse a single sessionID across tasks, it has to be passed as param "sessionID" inside your task. 
Please find an example below.

- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ config }}"
    name: "Test_Session"
  delegate_to: localhost
  register: session

- name: Create a Fibre Channel Network
  oneview_fc_network:
    hostname: <hostname>
    username: <username>
    password: <password>
    auth_login_domain: <domain_directory>
    api_version: 4000
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    data:
      name: "{{ network_name }}"
      fabricType: 'FabricAttach'
      linkStabilityTime: '30'
      autoLoginRedistribution: true
  no_log: true
  delegate_to: localhost
