### ISSUE TITLE
Playbook header

### ISSUE THREAD

**Issue by lkthomas** [HewlettPackard/oneview-ansible-collection#209]
Because the playbook is running locally, should you change the example by adding some local headers to the playbook lie this?

- hosts: localhost
  connection: local

**Comment by nabhajit-ray** [comment]
Hi, Will check and get back to you.

**Comment by alisha-k-kalladassery** [comment]
Hi lkthomas,

If you want to run it locally, you can add the header as you said. Also if you need a global change, you can have the same configuration added in /etc/ansible/hosts file.
