### ISSUE TITLE
assign static IP addresses during LE creation

### ISSUE THREAD

**Issue by vinicole** [HewlettPackard/oneview-ansible-collection#212]
Hello,
I create this new issue since I can't re-open [#86](https://github.com/HewlettPackard/oneview-ansible-collection/issues/86) which doesn't seem to be solved.
The code fix proposed in issue [#619](https://github.com/HewlettPackard/oneview-ansible/issues/619) returns the following error with oneview-ansible-collection:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: hpeOneView.exceptions.HPEOneViewException: ('The JSON cannot be mapped to array or collection.', {'errorCode': 'INVALID_NESTED_JSON_ELEMENT', 'message': 'The JSON cannot be mapped to array or collection.', 'details': 'The nested JSON "enclosureBaySettings" sent in the request is not a valid array or collection.', 'messageParameters': [], 'recommendedActions': ['Correct the JSON as appropriate array or collection and retry the request.'], 'errorSource': None, 'nestedErrors': [], 'data': {}})

RHEL 8.6
Python 3.6.8
Ansible 2.9.27
Oneview-ansible-collection 7.2.0

Could you please have a look?

Thanks,
V

_Originally posted by @vinicole in https://github.com/HewlettPackard/oneview-ansible-collection/issues/86#issuecomment-1248150620_

**Comment by alisha-k-kalladassery** [comment]
Hi Vinicole,
We will check and get back to you on this.

**Comment by alisha-k-kalladassery** [comment]
Hi Vinicole,

We checked it from our end and it seems working fine. Could you please share the OV version which you are using and the playbook so that we can check further.

Eg:
- name: Create a Logical Enclosure (available only on HPE Synergy)
  oneview_logical_enclosure:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    data:
      enclosureUris:
        - "{{ enclosures[1].uri }}"
        - "{{ enclosures[2].uri }}"
        - "{{ enclosures[0].uri }}"
      enclosureGroupUri: "{{ enclosure_groups['uri'] }}"
      name: "{{ contents.logical_enclosure.logical_enclosure_name }}"
      enclosureBaySettings:
        deviceBays:
          - enclosureNumber: 1
            bayNumber: 3
            manualAddresses:
              - type: "IPv4"
                ipAddress: "{{ ipaddr1 }}"
          - enclosureNumber: 2
            bayNumber: 3
            manualAddresses:
              - type: "IPv4"
                ipAddress: "{{ ipaddr2 }}"
        interconnectBays:
          - enclosureNumber: 1
            bayNumber: 2
            manualAddresses:
              - type: "IPv4"
                ipAddress: "{{ ipaddr3 }}"
  ignore_errors: true
  delegate_to: localhost
  when: (contents.logical_enclosure.variant == "Synergy" and enclosures is not none and enclosures is not undefined and 
        enclosure_groups is not none and enclosure_groups is not undefined)

**Comment by alisha-k-kalladassery** [comment]
Hi Vinicole,

We are closing this issue as there is no reply from your end. Please feel free to open a new issue if you encounter any issues again.
