### ISSUE TITLE
oneview_server_profile TypeError: sequence item 0: expected str instance, NoneType found 

### ISSUE THREAD

**Issue by dobey-xx** [HewlettPackard/oneview-ansible-collection#219]
Getting the follow error when trying to create a profile:

"/tmp/ansible_hpe.oneview.oneview_server_profile_payload___kih52j/ansible_hpe.oneview.oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 337, in __present\n File "/tmp/ansible_hpe.oneview.oneview_server_profile_payload___kih52j/ansible_hpe.oneview.oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 467, in __create_profile\n File "/tmp/ansible_hpe.oneview.oneview_server_profile_payload___kih52j/ansible_hpe.oneview.oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 702, in _auto_assign_server_profile\n File "/tmp/ansible_hpe.oneview.oneview_server_profile_payload___kih52j/ansible_hpe.oneview.oneview_server_profile_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_server_profile.py", line 556, in __get_available_server_hardware_uri\nTypeError: sequence item 0: expected str instance, NoneType found\n",

It's in a test environment so the user is Infrastructure admin. 

I followed the example as described here: https://github.com/HewlettPackard/oneview-ansible-collection/blob/master/roles/oneview_server_profile/tasks/main.yml

**Comment by alisha-k-kalladassery** [comment]
Hi 
Could you please confirm if you are creating server profile within a scope? If not could you please try the same.

Thanks

**Comment by dobey-xx** [comment]
Hi, 

According to this example, there is no need to set an scope uri.

- name: Create Server Profile without specifying a template
  oneview_server_profile:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    data:
      name: "{{ contents.server_profile.inventory_hostname }}"
      serverHardwareTypeName: "{{ contents.server_profile.server_hardware_type_name }}"
      enclosureGroupName: "{{ contents.server_profile.enclosure_group_name }}"
      description: "{{ contents.server_profile.server_profile_description }}"
  delegate_to: localhost

And if I try to use the parameter "InitialScopeUris", it throws the following error:

File \"/var/lib/awx/venv/env/lib/python3.6/site-packages/hpeOneView/connection.py\", line 413, in __do_rest_call\n    raise HPEOneViewException(body)\nhpeOneView.exceptions.HPEOneViewException: ('Unrecognized JSON field.', {'errorCode': 'UNRECOGNIZED_JSON_FIELD', 'message': 'Unrecognized JSON field.', 'details': 'The field named ServerHardwareTypeName near line 1, column 175 is not a valid field in this JSON object.', 'messageParameters': [], 'recommendedActions': ['Check the valid fields for this JSON object and remove or correct the unrecognized field.'], 'errorSource': None, 'nestedErrors': [], 'data': {}})\n",

**Comment by alisha-k-kalladassery** [comment]
Hi,

Please confirm the username which you are using.

**Comment by alisha-k-kalladassery** [comment]
Hi,

We understood the issue and have pushed the changes to branch sp_issue_219. Please confirm if it works fine for you.

**Comment by dobey-xx** [comment]
Hmm i'm using the ansible galaxy version directly from a requirements.yml, how can I pull this branche instead?

**Comment by alisha-k-kalladassery** [comment]
Hi,

Please follow the example file without any changes and kindly share the exact task which you are getting this error. It will help me to debug your issue further.

Thanks

**Comment by dobey-xx** [comment]
Hi, 

I've did some reverse engineering and it seems the provided example isn't correct.

The error states that there are unrecognized JSON fields,

- name: Create Server Profile without specifying a template
  oneview_server_profile:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    data:
      name: "{{ contents.server_profile.inventory_hostname }}"
      **serverHardwareTypeName: "{{ contents.server_profile.server_hardware_type_name }}"**
      **enclosureGroupName: "{{ contents.server_profile.enclosure_group_name }}"**
      description: "{{ contents.server_profile.server_profile_description }}"
  delegate_to: localhost

I've changed that to:

- name: Create Server Profile without specifying a template
  oneview_server_profile:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    data:
      name: "{{ contents.server_profile.inventory_hostname }}"
      serverHardwareName: "enclosure, bay"
      serialNumberType: "Phyiscal"
      description: "{{ contents.server_profile.server_profile_description }}"
  delegate_to: localhost

And the profile is created,
