### ISSUE TITLE
Server Profile Template module missing the newName property

### ISSUE THREAD

**Issue by frippe75** [HewlettPackard/oneview-ansible-collection#226]
A lot of the modules have been updated to take a newName parameter.
The oneview_server_profile_template.py has not been update. 

ER or Issue?

**Comment by nabhajit-ray** [comment]
Hi @frippe75 ,

Will check and get back to you

**Comment by alisha-k-kalladassery** [comment]
Hi Fredrik,

We have fixed this issue and it is available in master branch. It will be released as part of OV8.1 release.
