### ISSUE TITLE
Role for /rest/appliance/version

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/oneview-ansible-collection#237]
There is no Ansible role that allows checking the version of the appliance. Do note that there is a REST Api for this

**Comment by alisha-k-kalladassery** [comment]
Hi
We will look into this and get back to you.

**Comment by alisha-k-kalladassery** [comment]
Hi ,
We are closing this issue as we haven't heard from you. Please feel free to open a new issue if you have any further queries.
Thanks
