### ISSUE TITLE
Use of sessionID

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/oneview-ansible-collection#238]
As said in the readme, one should get a sessionID from OnveView to avoid sending authentication request for each task.
So once you get a sessionID, you don't need to use username/password anymore but sessionID instead.
However, when I look at the examples in the Readme, it's still passing username/password along with sessionID in subsequent calls to Oneview tasks.
Do we still need username/pass word if we have sessionID?

**Comment by alisha-k-kalladassery** [comment]
Hi 
You don't need to send username and password once sessionID is generated and passed. 
We will be changing the Readme. Thanks for the heads up.
