### ISSUE TITLE
Obtain Support data

### ISSUE THREAD

**Issue by pyfontan** [HewlettPackard/oneview-ansible-collection#258]
Hello,

Is there a possibility to obtain "Warranty and Contract" data of server-hardware from Oneview 8.30 with ansible collection ?

Thank you
Pierre-yves

**Comment by alisha-k-kalladassery** [comment]
Hi ,

We are looking into this. 

Thanks

**Comment by alisha-k-kalladassery** [comment]
Hi @pyfontan 

Are you looking for Remote Support related information?

Thanks

**Comment by pyfontan** [comment]
Hi @alisha-k-kalladassery ,

Yes, we are trying to obtain at least the End of Support date for our servers.

At first I thought that it would be possible easily with a simple modification of oneview_server_hardware_facts but it seems that HPe python SDK, which is used by this collection, doesn't support (yet ?) the "[Server Hardware Support](https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/support/server-hardware)" part of the API.

**Comment by alisha-k-kalladassery** [comment]
Hi @pyfontan 
We are not supporting Server Hardware  support as of now. We will add this to our backlog and will add it per priority.
Thanks for reaching out to us.

Thanks
