### ISSUE TITLE
unable to reapply complete server profile

### ISSUE THREAD

**Issue by avijitkulkarni** [HewlettPackard/oneview-ansible-collection#267]
Hello,

Greetings !

I am using below code to re-apply server profile, but every time once it runs it executes "Update" task on OneView and only updates missing firmware.
It says "BIOS settings will not be applied"

Could someone please suggest how to initiate a complete re-apply of server profile which includes everything ?

<img width="82" alt="image" src="https://github.com/HewlettPackard/oneview-ansible-collection/assets/144901913/f3779d3e-938d-4392-8590-693ae8946cb3">

We want to run this "Reapply" from ansible so that profile gets re-applied every time regardless of anything.

- name: apply server profile
      hpe.oneview.oneview_server_profile:
        hostname: "{{ hostname }}"
        auth_login_domain: "{{domain}}"
        username: "{{ user }}"
        password: "{{ password }}"
        sessionID: "{{ session }}"
        data:
            name: "{{ spname }}"
            state: "reapply"
      delegate_to: localhost
      register: apply_server_profile

ansible core --> 2.13.6
hpe.oneview --> 8.4.0

**Comment by akshith-gunasheelan** [comment]
Hi @avijitkulkarni thanks for your query. Currently we do not have the provision for re-apply state in our Ansible SDK. We have added this into our backlog and will take it as per our priority.

**Comment by akshith-gunasheelan** [comment]
Hi @avijitkulkarni , these steps will apply all settings , Thanks.

**Comment by akshith-gunasheelan** [comment]
Hi @avijitkulkarni , please let us know if we are good to close this issue now.

**Comment by avijitkulkarni** [comment]
Hello @akshith-gunasheelan,

Thank you so much for helping.
I was able to apply all settings after deleting and re-creating the server profile.
