### ISSUE TITLE
Not found roles

### ISSUE THREAD

**Issue by Sheetal-R** [HewlettPackard/oneview-ansible-collection#56]
roles not found for:
firmware drivers
sas interconnect
sas logical jbods
appliance time
subnet pool details

**Comment by nabhajit-ray** [comment]
Hi Sheetal,
We have taken your input.  As of now we have around 27 resources roles in ansible collection. Resources related to oneview settings and shared storage are in our backlog plan and we plan to add those in future.

**Comment by VenkateshRavula** [comment]
we have added support to ```firmware drivers```, ```appliance time``` and ```ipv4 subnet pool``` resources.

We have added below roles to our backlog.

- backup
- sas interconnect
- sas logical interconnect group
- sas logical jbods

**Comment by Sheetal-R** [comment]
Thank you very much😄
With Best Regards,
Sheetal

On 27-May-2021, at 11:04 AM, Venkatesh Ravula ***@***.***> wrote:

﻿

we have added support to firmware drivers, appliance time and ipv4 subnet pool resources.

We have added below roles to our backlog.

  *   backup
  *   sas interconnect
  *   sas logical interconnect group
  *   sas logical jbods

**Comment by VenkateshRavula** [comment]
These resources are already planned in our backlog. We will provide support to them in future releases. Closing this issue since this is not a defect.

**Comment by frippe75** [comment]
Looking for SAS logical jbods. Why not try to make the collection feature complete and on-par with the POSH module?
Abit of a shame. Maybe provide a way of generalizing these non-covered APIs to make it "more complete".

Now I will have to revert to the URI module and make a new login outside the module and create my JBODS.

**Comment by frippe75** [comment]
or maybe switching to the Terraform provider instead?

**Comment by nabhajit-ray** [comment]
Support for missing features are in our backlog. 
Currently, terraform provider is having lesser support compared to ansible collection.
