### ISSUE TITLE
module_utils _merge_connections_boot fails with TypeError

### ISSUE THREAD

**Issue by freedge** [HewlettPackard/oneview-ansible-collection#66]
```
in _merge_connections_boot
    existing_connection_map.update(dict(x[SPKeys.ID], x.copy()))
TypeError: dict expected at most 1 argument, got 2
```

at least on Python 3.8.3, dict takes only one argument.
This is surprising because the original module_utils (from the HPE  oneview ansible repository) works just fine. The issue is specific to the galaxy build (here, 1.2.1). Couldn't there be a single repository used for the collection build? How do you make sure changes are ported from one repository to the other? Are both repos following the same quality process ?

**Comment by VenkateshRavula** [comment]
We will try to fix this issue ASAP.

**Comment by VenkateshRavula** [comment]
The fix is merged to master and it will be available in upcoming release.
