### ISSUE TITLE
Enhancement Request: SPP "name" too restrictive

### ISSUE THREAD

**Issue by mleach8948** [HewlettPackard/oneview-ansible-collection#85]
Team, when working with oneview_firmware_driver_facts to extract the SPP URI for use in subsequent tasks, I can't figure out a way to easily pull the URI when querying OneView.  Because all SPPs are now "named" the same (like Service Pack for ProLiant or Service Pack for Synergy) for the SPP bundles could we add an additional attribute in the code "version" so that we can more easily obtain the URI of the desired SPP?  
I would love to see something like this:
- name: Get the baseline URI of the desired SPP
    oneview_firmware_driver_facts:
      config: "{{ config }}"
      **version: SY-2021.01.01**
      name: Service Pack for Synergy
  - set_fact:
      spp_uri: "{{ firmware_drivers[0].uri }}"
Thanks!

**Comment by nabhajit-ray** [comment]
Hi mleach8948,
Thanks for pointing this out. We will check this and get back to you.

**Comment by nabhajit-ray** [comment]
Enhancement added to our backlog and will be included in next release

**Comment by VenkateshRavula** [comment]
You can refer to below example to get the facts about firmware drivers using name and version.

https://github.com/HewlettPackard/oneview-ansible-collection/blob/master/roles/oneview_firmware_driver_facts/tasks/main.yml#L28-L33
