### ISSUE TITLE
Clarify on the readme the installation steps for the python module dependency

### ISSUE THREAD

**Issue by lucas-benedito** [HewlettPackard/oneview-ansible-collection#90]
ISSUE TYPE
 - Improvement

SUMMARY

- Add the pip install step after ansible-galaxy as a requirement for using the module for additional clarity on the readme.
~~~
To install the required python modules:
`pip install hpeOneView`
~~~

**Comment by nabhajit-ray** [comment]
Thanks for pointing this. Will add this .

**Comment by SHANDCRUZ** [comment]
Hi @lucas-benedito the installation step of python dependency module is already taken care by **pip install -r requirements.txt** command.

**Comment by lucas-benedito** [comment]
Hello @SHANDCRUZ, that is described if you are installing from GitHub download. In Automation Hub however, the requirements file isn't visible and thus creating confusion.

**Comment by nabhajit-ray** [comment]
Hi @lucas-benedito , the requirements.txt is there in the tar file we get in Automation Hub. Can you confirm you are not seeing the requirements.txt file? The automation hub is link is
 https://cloud.redhat.com/ansible/automation-hub/repo/published/hpe/oneview

**Comment by lucas-benedito** [comment]
Hello, when installing using `ansible-galaxy collection install hpe.oneview` a user will not check the installation folder for the requirements file. For example, when using the collection in Ansible Tower.
With that said, it would be clearer to add the required `pip install hpeOneView` on the readme and not only the `pip install -r requirements.yml`.

**Comment by SHANDCRUZ** [comment]
Hi @lucas-benedito the installation step of dependency module has been modified and merged into the branch. I hope it will clarify the installation steps for installing the module dependency. please feel free to reopen if any further improvements required.
